force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/Alcohol__c.field-meta.xml
<CustomField>
    <fullName>Alcohol__c</fullName>
    <label>Alcohol %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/brewery_id__c.field-meta.xml
<CustomField>
    <fullName>brewery_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>brewery_id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/brewery_Name__c.field-meta.xml
<CustomField>
    <fullName>brewery_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>brewery_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Remaining_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Quantity__c</fullName>
    <formula>Total_Quantity__c -  Consumed_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tags</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BeerSearchAuraService.cls
public class BeerSearchAuraService {
	@AuraEnabled
    public static List<sObject> searchBeer(String searchParam){
        String likeParam = '%' +searchParam+'%';
        String Query = '';
        if(searchParam != null){
           Query  = 'Select Id, Name,Alcohol__c,brewery_id__c, brewery_Name__c, Id__c, Price__c,Remaining_Quantity__c, Tags__c, Total_Quantity__c From Beer__c Where Name Like :likeParam LIMIT 50 ';
        }else{
           Query  = 'Select Id, Name,Alcohol__c,brewery_id__c, brewery_Name__c, Id__c, Price__c,Remaining_Quantity__c, Tags__c, Total_Quantity__c From Beer__c LIMIT 50 '; 
        }
        
        List<SObject> sObjectList = Database.query(Query);
        return sObjectList;
    }
}